# baseURL = "https://blog.openstates.org/"
baseURL = "https://agitated-raman-c9cab7.netlify.com/"
languageCode = "en-us"
title = "Open States"
theme = "beautifulhugo"
googleAnalytics = "UA-143711479-2"

[permalinks]
 post = ":filename"

[taxonomies]
 author = "author"

[Params]
 subtitle = "Latest updates from the Open States team"
 logo = "img/openstates_icon_white.png"
 favicon = "img/favicon.ico"
 rss = true
 socialShare = true
 showRelatedPosts = true

[Author]
 # email = "contact@openstates.org"
 github = "openstates"
 twitter = "openstates"
