baseURL = "https://blog.openstates.org/"
languageCode = "en-us"
title = "Open States"
theme = "beautifulhugo"
googleAnalytics = "UA-143711479-2"

[permalinks]
 post = ":filename"

[Params]
 subtitle = "Latest updates from the Open States team"
 logo = "img/openstates_icon_white.png"
 favicon = "img/favicon.ico"
 rss = true
 socialShare = true
 showRelatedPosts = true

[Author]
 # email = "contact@openstates.org"
 github = "openstates"
 twitter = "openstates"


[[menu.main]]
    name = "About"
    url = "https://openstates.org/about/"
    weight = 2

[[menu.main]]
    name = "OpenStates.org"
    url = "https://openstates.org/"
    weight = 1

[[menu.main]]
    name = "Donate"
    url = "https://openstates.org/donate/"
    weight = 5
